### ISSUE TITLE
Support for atomic increments

### ISSUE THREAD

**Issue by tobsch** [infinispan/ruby-client#1]
Hi there,

it would be neat to see you supporting atomic increments.
Is that planned in near-future?

Best,

Tobias

**Comment by lance** [comment]
Something like this?

<code>
cache.increment('a key')     # increment by 1
cache.increment('akey', 4)  # increment by 4
cache.decrement('akey')     # decrement by 1
cache.decrement('akey', 2) #decrement by 2
</code>

**Comment by tobsch** [comment]
yeah, something like that.
am i blind? grepped through the source and you sound like i'm mistaken?

**Comment by lance** [comment]
Sorry about that! I did not mean to close the issue. And you are correct. There is no support for this at the moment, but that should be relatively straightforward to implement.

**Comment by tobsch** [comment]
thanks :)

**Comment by lance** [comment]
Tobias

The increment and decrement methods are available with the latest push https://github.com/torquebox/infinispan-ruby-client/commit/f3ef30d4114929a10f2814ee5e8221eb85a82997

Let me know how it works out for you.

Lance
